# Your Info
__Name__: Dinh

__PDX Email__: dinhn@pdx.edu

__Collaborators__: Kevin, EPAK, John, Brian

# NumPy Workouts

This set of exercises provides an opportunity to practice working with NumPy arrays.

Carefully read each exercise and complete the task to the best of your ability.

## 1. Importing NumPy

#### 1.1 Import the NumPy package under the name `np`

In [2]:

# Import the NumPy package under the name np
import numpy as np


#### 1.2 Print the NumPy version and the configuration

In [3]:
print(np.__version__)
print(np.show_config())


2.2.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.7/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.7/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.28
  lapack:
    detection method: pkgconfig
    found: true
    include directory: /opt/_internal/cpython-3.12.7/lib/python3.12/site-packages/scipy_openblas64/include
    lib directory: /opt/_internal/cpython-3.12.7/lib/python3.12/site-packages/scipy_openblas64/lib
    name: scipy-openblas
    openblas configuration: OpenBLAS 0.3.28  USE64BITINT DYNAMIC_ARCH NO_AFFINITY
      Haswell MAX_THREADS=64
    pc file directory: /project/.openblas
    version: 0.3.28
Compilers:
  c:
    commands: cc
    linker: ld.bfd


## 2. Creating Arrays

#### 2.1 Create a 1D array of 30 zeros

In [31]:
zeros = np.zeros(30)
print(zeros)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0.]


#### 2.2 Create a 2D array with 3 rows and 2 columns filled with Ones

In [32]:
ones = np.ones((3, 2))
print(ones)


[[1. 1.]
 [1. 1.]
 [1. 1.]]


#### 2.3 Create a 1D Array containing the even numbers from 0 to 10 (inclusive)

In [33]:
evens = np.arange(0, 11, 2)
print(evens)


[ 0  2  4  6  8 10]


#### 2.4 Create a new array that is the result of multiplying each element of `numpy_array` by 3

In [34]:
numpy_array = np.array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

mul_3 = numpy_array * 3
print(mul_3)


[ 6 12 18 24 30 36 42 48 54 60]


#### 2.5 Create an Array with a shape of 5 rows and 4 columns, filled with Zeros

In [35]:
array54 = np.zeros((5, 4))
print(array54)


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 2.6 Check the shape and dimensions of the `sample_array` below:

In [9]:
sample_array = np.array([[1, 2, 3], [4, 5, 6]])

print(sample_array.shape)
print(sample_array.ndim)


(2, 3)
2


#### 2.7 Create a size-10 array of zeros except the fifth value is 1

In [36]:
size_10 = np.zeros(10)
size_10[4] = 1
print(size_10)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 2.8 Create an arrray with values ranging from 10 to 49

In [37]:
array_10_49 = np.arange(10, 50)
print(array_10_49)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 2.9 Create a 3x3 array with values ranging from 0 to 8

In [38]:
array3_3 = np.arange(0, 9).reshape(3, 3)
print(array3_3)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 2.10 Create a 3x3x3 array with random values

In [39]:
array3_3_3 = np.random.random((3, 3, 3))
print(array3_3_3)


[[[0.31446435 0.59957321 0.13220044]
  [0.66886333 0.09265744 0.95771319]
  [0.34176651 0.48203538 0.83998279]]

 [[0.19068309 0.34523364 0.72897898]
  [0.79272942 0.92549454 0.92966726]
  [0.68906952 0.14980289 0.0087154 ]]

 [[0.30466111 0.5938765  0.49184169]
  [0.33988194 0.91704268 0.57230576]
  [0.33754401 0.18390962 0.31634219]]]


## 3. Operations

#### 3.1 Element-Wise Operations

1. Create a NumPy array arr with the values [1, 2, 3, 4, 5].
2. Add 5 to each element of the array.
3. Multiply each element of the array by 2.
4. Calculate the square of each element in the array.

In [20]:
# Create a NumPy array arr with the values [1, 2, 3, 4, 5].
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# Add 5 to each element of the array.
arr_plus_5 = arr + 5
print(arr_plus_5)

# Multiply each element of the array by 2.
arr_times_2 = arr * 2
print(arr_times_2)

# Calculate the square of each element in the array.
arr_squared = arr ** 2
print(arr_squared)


[1 2 3 4 5]
[ 6  7  8  9 10]
[ 2  4  6  8 10]
[ 1  4  9 16 25]


#### 3.2 Array Arthmetic

1. Create two NumPy arrays: `arr1 = np.array([10, 20, 30])` and `arr2 = np.array([1, 2, 3])`.
2. Add `arr1` and `arr2` element-wise.
3. Subtract `arr2` from `arr1` element-wise.
4. Multiply `arr1` and `arr2` element-wise.
5. Divide `arr1` by `arr2` element-wise.

In [23]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([1, 2, 3])

print(arr1)
print(arr2)

# Add arr1 and arr2 element-wise.
arr_sum = arr1 + arr2
print(arr_sum)

# Subtract arr2 from arr1 element-wise.
arr_diff = arr1 - arr2
print(arr_diff)

# Multiply arr1 and arr2 element-wise.
arr_product = arr1 * arr2
print(arr_product)

# Divide arr1 by arr2 element-wise.
arr_division = arr1 / arr2
print(arr_division)


[10 20 30]
[1 2 3]
[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


## 4. Statistical Methods

#### 4.1 Aggregation

1. Create a NumPy array `data` containing 30 random numbers.
2. Find the sum of all elements in `data`.
3. Find the minimum value in `data`.
4. Find the maximum value in `data`.
5. Calculate the mean of the elements in `data`.

In [26]:
# Create a NumPy array data containing 30 random numbers.
data = np.random.rand(30)
print(data)

# Find the sum of all elements in data.
sum_data = np.sum(data)
print(sum_data)

# Find the minimum value in data.
min_data = np.min(data)
print(min_data)

# Find the maximum value in data.
max_data = np.max(data)
print(max_data)

# Calculate the mean of the elements in data.
mean_data = np.mean(data)
print(mean_data)


[0.55910653 0.41445819 0.09296421 0.40847489 0.09003737 0.57136566
 0.87050006 0.68778348 0.83787902 0.51011326 0.04753467 0.57607886
 0.49682188 0.8851723  0.17415767 0.07537055 0.56277238 0.54781567
 0.0335468  0.55029744 0.01049576 0.16211474 0.79769585 0.83929877
 0.23005812 0.2108688  0.29488513 0.87945099 0.42493921 0.19701126]
13.039069512114395
0.01049576128797769
0.8851722957086403
0.4346356504038132


## 5. Bonus

#### 5.1 Checkerboard 

1. Create an 8x8 array and fill it with a checkerboard pattern

In [41]:
# Create an 8x8 array and fill it with a checkerboard pattern
checkerboard = np.zeros((8, 8))
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print(checkerboard)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 5.2 Matrix

1. Create a 2D NumPy array `matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])`.
2. Calculate the sum of all elements in the `matrix`.
3. Calculate the sum of each row in the `matrix`.
4. Calculate the sum of each column in the `matrix`.

In [30]:
# Create a 2D NumPy array matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]).
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

# Calculate the sum of all elements in the matrix.
sum_matrix = np.sum(matrix)
print(sum_matrix)

# Calculate the sum of each row in the matrix.
sum_rows = np.sum(matrix, axis=1)
print(sum_rows)

# Calculate the sum of each column in the matrix.
sum_columns = np.sum(matrix, axis=0)
print(sum_columns)


[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[ 6 15 24]
[12 15 18]


### Submitting Your Assignment

Please follow these steps to submit your work:

1. Ensure your name and the names of any collaborators are clearly stated in the [Your Info](#Your-Info) section at the top of the notebook.
2. Download your completed notebook as a `.ipynb` file.
3. Upload this `.ipynb` file to the designated assignment submission area in Canvas.